Repository fylein/fyle-intacct-api, pull requests merged in 2024-11, with the labels that each got.

#571 feat: Add objectLabel as attribute type for user defined dimensions
  apps/sage_intacct/utils.py
  scripts/python/update-user-defined-dimension-attribute-type.py
Labels: size/S

#572 Fix: Fix user defined dimensions
  apps/sage_intacct/utils.py
Labels: deploy, size/XS

#573 fix: remove sentry transaction sampling
  fyle_intacct_api/sentry.py
Labels: size/XS

#574 fix: add index to cost type model
  apps/sage_intacct/migrations/0030_auto_20241112_0425.py
  apps/sage_intacct/models.py
Labels: size/S

#576 fix: add unique constraint in task_logs for expense_group
  apps/tasks/migrations/0010_alter_tasklog_expense_group.py
  apps/tasks/models.py
Labels: size/S

#577 feat: auto enable accounting period
  apps/workspaces/migrations/0039_alter_configuration_change_accounting_period.py
  apps/workspaces/models.py
  requirements.txt
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
Labels: size/S

#575 feat: handle posted at
  apps/fyle/migrations/0034_expense_is_posted_at_null.py
  apps/fyle/models.py
  apps/workspaces/migrations/0039_alter_configuration_change_accounting_period.py
  apps/workspaces/models.py
  requirements.txt
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
Labels: size/M

#579 fix: posted at null
  apps/fyle/models.py
  tests/test_fyle/fixtures.py
  tests/test_workspaces/fixtures.py
Labels: size/S

#581 Fix: Rounding Amount in payload to 2 points
  apps/sage_intacct/utils.py
Labels: size/XS

#578 feat: masked card num employee name description
  apps/fyle/migrations/0035_expense_masked_corporate_card_number.py
  apps/fyle/models.py
  apps/sage_intacct/models.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_fyle/fixtures.py
  tests/test_workspaces/fixtures.py
Labels: size/M

#582 feat: Trim memo and date in exports
  apps/sage_intacct/models.py
Labels: size/XS

#580 feat: Add support for internal APIs
  apps/internal/__init__.py
  apps/internal/actions.py
  apps/internal/apps.py
  apps/internal/migrations/__init__.py
  apps/internal/urls.py
  apps/internal/views.py
  apps/sage_intacct/utils.py
  apps/workspaces/permissions.py
  fyle_intacct_api/settings.py
  fyle_intacct_api/urls.py
  tests/test_internal/__init__.py
  tests/test_internal/test_actions.py
  tests/test_internal/test_views.py
Labels: size/L
