Repository fylein/fyle-intacct-api, pull requests merged in 2024-09, with the labels that each got.

#556 chore: Added github action
  .github/pull_request_template.md
  .github/workflows/pr_size.yml
Labels: size/S

#548 Max retry payment Limit with test
  apps/sage_intacct/migrations/0029_auto_20240902_1511.py
  apps/sage_intacct/models.py
  apps/sage_intacct/tasks.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_sageintacct/test_tasks.py
Labels: deploy, size/M

#558 fix: Adding allocation to both debit and credit line of Journal Entry
  apps/sage_intacct/utils.py
  tests/test_sageintacct/fixtures.py
Labels: size/M

#562 fix: send unique task name in payload
  apps/sage_intacct/dependent_fields.py
  tests/test_sageintacct/test_dependent_fields.py
Labels: size/XS

#561 fix: PR Size CI Version Update
  .github/workflows/pr_size.yml
Labels: size/XS

#551 feat: Add generators in all the sage dimension sync
  apps/sage_intacct/utils.py
  tests/test_mappings/test_imports/test_modules/fixtures.py
  tests/test_mappings/test_imports/test_modules/test_base.py
  tests/test_mappings/test_imports/test_modules/test_categories.py
  tests/test_mappings/test_imports/test_modules/test_cost_centers.py
  tests/test_mappings/test_imports/test_modules/test_expense_custom_fields.py
  tests/test_mappings/test_imports/test_modules/test_merchants.py
  tests/test_mappings/test_imports/test_modules/test_tax_groups.py
  tests/test_mappings/test_tasks.py
  tests/test_sageintacct/fixtures.py
  tests/test_sageintacct/test_tasks.py
  tests/test_sageintacct/test_utils.py
Labels: deploy, size/XL
