Repository fylein/fyle-intacct-api, pull requests merged in 2024-10, with the labels that each got.

#557 fix: integration stats
  requirements.txt
Labels: deploy, size/XS

#563 feat: Fix generator code and remove loggers
  apps/sage_intacct/utils.py
Labels: size/XS

#564 feat: Added limits to attributes
  apps/sage_intacct/utils.py
  tests/test_mappings/test_imports/test_modules/test_categories.py
  tests/test_mappings/test_imports/test_modules/test_expense_custom_fields.py
  tests/test_mappings/test_imports/test_modules/test_tax_groups.py
  tests/test_mappings/test_tasks.py
  tests/test_sageintacct/test_utils.py
Labels: size/L

#565 feat: Log worker Id for export async task
  apps/sage_intacct/tasks.py
  fyle_intacct_api/logging_middleware.py
  fyle_intacct_api/settings.py
Labels: size/M

#568 feat: Add middleware to log all post requests
  fyle_intacct_api/logging_middleware.py
  fyle_intacct_api/settings.py
Labels: size/S

#569 feat: Add extensive loggers in sdk
  fyle_intacct_api/logging_middleware.py
  fyle_intacct_api/settings.py
  requirements.txt
Labels: size/XS

#570 fix: default auto map employee to Name for CCC expenses export only
  apps/workspaces/signals.py
Labels: size/XS

#566 refactor: remove batching from dep field import
  apps/sage_intacct/dependent_fields.py
  apps/sage_intacct/utils.py
  tests/test_sageintacct/test_dependent_fields.py
Labels: deploy, size/M
