Repository fylein/fyle-intacct-api, pull requests merged in 2025-04, with the labels that each got.

#647 fix: Local dev fix
  docker-compose-pipeline.yml
Labels: size/XS

#633 chore: Add Security Scan Workflow
  .github/workflows/security-scan.yml
Labels: size/S

#651 fix: migration dependencies for new setup
  .flake8
  requirements.txt
Labels: size/XS

#650 fix: move payment sync to bulk read
  apps/sage_intacct/tasks.py
  apps/sage_intacct/utils.py
  tests/test_mappings/test_exceptions.py
  tests/test_sageintacct/fixtures.py
  tests/test_sageintacct/test_tasks.py
Labels: size/M

#649 chore: Remove dead flags
  apps/workspaces/apis/export_settings/serializers.py
  apps/workspaces/migrations/0042_remove_configuration_is_simplify_report_closure_enabled.py
  apps/workspaces/models.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_workspaces/fixtures.py
  tests/test_workspaces/test_apis/test_export_settings/fixtures.py
Labels: size/M

#626 Feat: Add order to location, department and others
  apps/sage_intacct/models.py
Labels: deploy, size/M

#655 fix: Bulk attachment
  apps/sage_intacct/tasks.py
  apps/sage_intacct/utils.py
  tests/test_sageintacct/test_utils.py
Labels: size/M

#659 fix: python build
  Dockerfile
Labels: size/XS

#660 chore: Upgrade sage sdk
  requirements.txt
Labels: size/XS

#662 chore: Increase timeout
  fyle_intacct_api/settings.py
Labels: size/XS

#652 feat: cache vendor search
  .github/workflows/codecov.yml
  .github/workflows/pytest.yml
  apps/sage_intacct/queue.py
  apps/sage_intacct/tasks.py
  apps/sage_intacct/utils.py
  tests/test_sageintacct/test_tasks.py
  tests/test_sageintacct/test_utils.py
Labels: deploy, size/L

#661 chore: add migration files
  apps/internal/migrations/0009_auto_generate_sql.py
Labels: size/XS

#656 chore: Add expense index & handle post accounting export summary
  apps/fyle/actions.py
  apps/fyle/migrations/0040_expense_expenses_account_ff34f0_idx_and_more.py
  apps/fyle/migrations/0041_alter_expense_imported_from.py
  apps/fyle/models.py
  apps/fyle/tasks.py
  apps/internal/tasks.py
  apps/sage_intacct/tasks.py
  apps/tasks/migrations/0013_alter_tasklog_triggered_by.py
  requirements.txt
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_fyle/test_actions.py
Labels: size/M

#664 fix: worker retries
  .github/workflows/codecov.yml
  workers/export/worker.py
Labels: size/S

#665 fix: skipped direct export sync
  apps/fyle/tasks.py
Labels: deploy, size/S

#666 fix: post accounting export summary params
  apps/fyle/tasks.py
  apps/sage_intacct/tasks.py
Labels: size/S

#667 feat: move to v1
  apps/users/views.py
  requirements.txt
  tests/conftest.py
  tests/test_fyle/test_actions.py
  tests/test_fyle/test_views.py
  tests/test_mappings/test_imports/test_modules/test_base.py
  tests/test_mappings/test_imports/test_modules/test_categories.py
  tests/test_mappings/test_imports/test_modules/test_cost_centers.py
  tests/test_mappings/test_imports/test_modules/test_expense_custom_fields.py
  tests/test_mappings/test_imports/test_modules/test_merchants.py
  tests/test_mappings/test_imports/test_modules/test_tax_groups.py
  tests/test_mappings/test_signals.py
  tests/test_mappings/test_tasks.py
  tests/test_sageintacct/test_dependent_fields.py
  tests/test_users/test_helpers.py
  tests/test_workspaces/test_tasks.py
Labels: deploy, size/M

#668 chore: handle auto map
  apps/mappings/tasks.py
Labels: size/XS

#669 chore: skip summary post
  apps/fyle/actions.py
  apps/internal/tasks.py
  apps/workspaces/migrations/0043_configuration_skip_accounting_export_summary_post.py
  apps/workspaces/models.py
  apps/workspaces/serializers.py
  requirements.txt
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
Labels: size/M

#671 fix: intacct export url
  apps/sage_intacct/tasks.py
  scripts/python/fill-accounting-export-summary.py
  tests/test_sageintacct/fixtures.py
Labels: size/XS

#672 fix: last spent at configuration
  apps/fyle/models.py
  apps/sage_intacct/models.py
Labels: size/XS

#670 Feat: Expenses can be skipped after being imported to integration
  apps/fyle/actions.py
  apps/fyle/models.py
  apps/fyle/tasks.py
  tests/test_fyle/test_task.py
Labels: size/M

#673 fix: task get api
  apps/tasks/views.py
  tests/test_tasks/test_views.py
Labels: size/S

#674 fix: tasks get call
  apps/tasks/views.py
Labels: deploy, size/XS
