Repository fylein/fyle-intacct-api, pull requests merged in 2025-05, with the labels that each got.

#676 fix: Expense group get for internal fun
  apps/internal/tasks.py
Labels: size/XS

#677 fix: add expense group condition
  apps/internal/tasks.py
Labels: size/XS

#675 fix: credit card misc not found error
  apps/exceptions.py
  apps/sage_intacct/models.py
  apps/sage_intacct/tasks.py
  tests/test_sageintacct/test_tasks.py
Labels: size/M

#679 fix: Reduce paginator size for accounting export summary post
  apps/fyle/actions.py
  apps/internal/tasks.py
Labels: size/XS

#680 Feat: Remove Timeout from qcluster settings
  fyle_intacct_api/settings.py
Labels: size/XS

#681 fix: skip export
  apps/sage_intacct/queue.py
  tests/test_fyle/test_queue.py
Labels: size/XS

#682 fix: skip direct export call
  apps/fyle/actions.py
  apps/sage_intacct/queue.py
Labels: size/S

#683 Feat: Bump up integrations platform connector
  requirements.txt
Labels: size/XS

#686 Feat: Fix bug where expenses custom field be empty dict
  apps/sage_intacct/models.py
Labels: size/S

#687 fix: cost code standalone import
  apps/internal/migrations/00010_auto_generated_sql.py
  apps/sage_intacct/dependent_fields.py
  apps/sage_intacct/migrations/0031_costcode.py
  apps/sage_intacct/models.py
  apps/sage_intacct/utils.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_sageintacct/conftest.py
  tests/test_sageintacct/test_dependent_fields.py
  tests/test_sageintacct/test_utils.py
Labels: size/L

#689 fix: typo in migration dep
  apps/internal/migrations/00010_auto_generated_sql.py
Labels: size/XS

#690 fix: remove migration
  apps/internal/migrations/00010_auto_generated_sql.py
Labels: size/XS

#688 Feat: Add support for Corporate card to vendor mapping
  apps/fyle/tasks.py
  apps/sage_intacct/models.py
  apps/workspaces/signals.py
  tests/test_sageintacct/test_models.py
  tests/test_sageintacct/test_signal.py
Labels: deploy, size/M

#691 fix: Direct export -ve expense, token bug
  apps/fyle/models.py
  apps/fyle/tasks.py
Labels: size/S

#684 feat: Je single line item
  apps/sage_intacct/utils.py
  apps/workspaces/apis/advanced_settings/serializers.py
  apps/workspaces/migrations/0044_configuration_je_single_credit_line.py
  apps/workspaces/models.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_sageintacct/test_utils.py
  tests/test_workspaces/fixtures.py
  tests/test_workspaces/test_apis/test_advanced_settings/fixtures.py
Labels: size/L

#692 chore: Add direct export loggers
  apps/fyle/actions.py
  fyle_intacct_api/logging_middleware.py
Labels: size/S

#693 fix: rounding for JE
  apps/sage_intacct/utils.py
Labels: size/XS

#696 fix: task id none
  apps/sage_intacct/models.py
  apps/sage_intacct/utils.py
Labels: size/M

#694 fix: update email redirect url from settings to admin app
  apps/workspaces/tasks.py
Labels: size/XS

#698 fix: Skip Export post accounting export Summary when not direct export
  apps/sage_intacct/queue.py
Labels: size/XS
