Repository fylein/fyle-intacct-api, pull requests merged in 2025-03, with the labels that each got.

#610 feat: patch integrations-settings-api on export errors
  apps/fyle/helpers.py
  apps/sage_intacct/helpers.py
  apps/sage_intacct/tasks.py
  tests/test_sageintacct/fixtures.py
  tests/test_sageintacct/test_tasks.py
Labels: size/M

#620 feat: Restructure Direct Export
  .flake8
  apps/fyle/helpers.py
  apps/fyle/queue.py
  apps/fyle/tasks.py
  apps/sage_intacct/queue.py
  apps/sage_intacct/tasks.py
  apps/workspaces/actions.py
  tests/test_fyle/test_helpers.py
  tests/test_fyle/test_queue.py
  tests/test_sageintacct/test_tasks.py
Labels: deploy, size/L

#624 fix: django vul
  requirements.txt
Labels: size/XS

#622 feat: retire exports
  apps/sage_intacct/queue.py
  apps/tasks/migrations/0011_tasklog_is_retired.py
  apps/tasks/models.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_fyle/test_queue.py
Labels: size/XL

#625 fix: TLS vulnerability
  .flake8
  Dockerfile
  docker-compose-pipeline.yml
  init.sql
  tests/conftest.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sh
Labels: size/S

#621 feat: show display name in UI, fix user dimension in export payload
  apps/fyle/helpers.py
  apps/fyle/views.py
  apps/sage_intacct/models.py
  apps/sage_intacct/utils.py
  apps/sage_intacct/views.py
  fyle_intacct_api/settings.py
  fyle_intacct_api/tests/settings.py
  requirements.txt
  tests/test_fyle/test_helpers.py
Labels: size/M

#627 fix: Add 1 general post accounting call after last export
  apps/sage_intacct/tasks.py
Labels: size/XS

#628 fix: revert "feat: show display name in UI, fix user dimension in export payload (#621)
  apps/fyle/helpers.py
  apps/fyle/views.py
  apps/sage_intacct/models.py
  apps/sage_intacct/utils.py
  apps/sage_intacct/views.py
  fyle_intacct_api/settings.py
  fyle_intacct_api/tests/settings.py
  requirements.txt
  tests/test_fyle/test_helpers.py
Labels: size/M

#629 Feat: Add health check
  Dockerfile
  health_check.sh
Labels: size/S

#634 feat: Show display name
  apps/fyle/helpers.py
  apps/fyle/views.py
  apps/mappings/signals.py
  apps/sage_intacct/models.py
  apps/sage_intacct/utils.py
  apps/sage_intacct/views.py
  apps/workspaces/urls.py
  fyle_intacct_api/settings.py
  fyle_intacct_api/tests/settings.py
  requirements.txt
  tests/test_fyle/test_helpers.py
  tests/test_sageintacct/test_models.py
  tests/test_workspaces/test_apis/test_import_settings/test_views.py
Labels: size/M

#635 fix: Show display name custom field fix
  apps/fyle/helpers.py
Labels: size/XS

#636 fix: display name fetch from fyle
  apps/fyle/helpers.py
  tests/test_fyle/test_helpers.py
  tests/test_fyle/test_views.py
  tests/test_mappings/test_signals.py
Labels: size/S

#631 fix: Run container with non root user
  Dockerfile
  docker-compose-pipeline.yml
Labels: size/XS

#639 fix: Vendor Get
  apps/sage_intacct/utils.py
Labels: size/XS

#637 feat: mapping setting change 1
  apps/workspaces/apis/export_settings/serializers.py
  apps/workspaces/apis/export_settings/triggers.py
  apps/workspaces/apis/import_settings/triggers.py
  tests/test_workspaces/test_apis/test_export_settings/test_triggers.py
Labels: deploy, size/M

#640 fix: help article domain
  docker-compose-pipeline.yml
Labels: size/XS

#641 fix: is_category_mapping_changed
  apps/workspaces/apis/export_settings/serializers.py
Labels: size/XS

#642 chore: bump connector version
  requirements.txt
Labels: size/XS

#643 Feat: Checking failing flake
  apps/workspaces/apis/import_settings/triggers.py
Labels: size/XS

#644 Feat: Add updated_at to updates and bulk updates
  apps/fyle/actions.py
  apps/fyle/models.py
  apps/fyle/tasks.py
  apps/mappings/imports/modules/base.py
  apps/mappings/signals.py
  apps/mappings/tasks.py
  apps/sage_intacct/dependent_fields.py
  apps/sage_intacct/tasks.py
  apps/workspaces/apis/import_settings/triggers.py
  apps/workspaces/signals.py
  tests/test_sageintacct/test_dependent_fields.py
Labels: size/M
