Repository fylein/fyle-intacct-api, pull requests merged in 2025-07, with the labels that each got.

#736 fix: Last Exported at date
  apps/sage_intacct/actions.py
Labels: size/S

#726 fix: bugfixes in cursor-generated code
  apps/fyle/helpers.py
  apps/internal/actions.py
  apps/internal/helpers.py
  apps/internal/serializers.py
  apps/internal/services/__init__.py
  apps/internal/services/e2e_setup.py
  apps/internal/services/fixture_factory.py
  apps/internal/views.py
  tests/test_internal/fixtures.py
  tests/test_internal/test_actions.py
  tests/test_internal/test_helpers.py
  tests/test_internal/test_services.py
  tests/test_internal/test_views.py
Labels: size/XL

#740 Feat: Add custom throttling class
  fyle_intacct_api/settings.py
  fyle_intacct_api/throttles.py
Labels: size/S

#741 fix: set onboarding state in e2e setup
  apps/internal/services/e2e_setup.py
Labels: deploy, size/S

#744 fix: add upper limit to udd
  apps/sage_intacct/utils.py
  tests/test_sageintacct/fixtures.py
  tests/test_sageintacct/test_utils.py
Labels: size/S

#743 fix: update mock expense group data in e2e setup
  apps/internal/services/e2e_setup.py
  apps/internal/services/fixture_factory.py
  tests/test_internal/test_services.py
Labels: deploy, size/S

#752 fix: use workspace id instead of org id in e2e delete payload
  apps/internal/serializers.py
  apps/internal/views.py
  tests/test_internal/fixtures.py
  tests/test_internal/test_views.py
Labels: size/S

#754 fix: disable imports and deactivate existing expense attributes in e2e
  apps/internal/services/e2e_setup.py
  requirements.txt
Labels: deploy, size/XS

#756 fix: skip dependent field settings creation in e2e setup
  apps/internal/services/e2e_setup.py
  apps/internal/services/fixture_factory.py
Labels: deploy, size/M

#760 chore: fix new setup migration
  apps/internal/migrations/0001_auto_generated_sql.py
Labels: size/XS
