Repository fylein/fyle-intacct-api, pull requests merged in 2025-09, with the labels that each got.

#779 feat: break chain tasks into smaller chunks
  apps/sage_intacct/actions.py
  apps/sage_intacct/queue.py
  apps/sage_intacct/tasks.py
Labels: staging_deploy, size/M

#784 fix: cc date option changing from spent_at to posted_at
  apps/fyle/helpers.py
Labels: size/XS

#759 feat: handle fund_source change for expenses
  .github/workflows/pytest.yml
  apps/fyle/tasks.py
  tests/test_fyle/conftest.py
  tests/test_fyle/test_models.py
  tests/test_fyle/test_task.py
Labels: staging_deploy, size/XL

#786 fix: Handle deleted expenses post accounting summary
  apps/fyle/actions.py
  requirements.txt
  tests/test_fyle/test_actions.py
Labels: size/M

#789 feat: add caching for sync and refresh calls
  apps/fyle/views.py
  apps/sage_intacct/views.py
  apps/workspaces/enums.py
  tests/test_sageintacct/test_views.py
Labels: size/M

#793 fix: Fix migraton 2
  apps/internal/migrations/0017_auto_generated_sql.py
Labels: size/XS
