Repository fylein/fyle-intacct-api, pull requests merged in 2025-08, with the labels that each got.

#767 fix: Patch Integration Return
  .pre-commit-config.yaml
  apps/workspaces/tasks.py
Labels: size/XS

#769 fix: Vendor creationg (Vendor id length)
  apps/sage_intacct/utils.py
  tests/test_sageintacct/test_utils.py
Labels: size/XS

#770 Fix: Remove retry failed exports
  apps/workspaces/tasks.py
Labels: size/XS

#771 chore: add drstrange deploy
  .github/workflows/drstrange_deployment.yml
  .github/workflows/staging_deployment.yml
Labels: size/M, drstrange_deploy

#772 fix: drstrange deploy
  .github/workflows/drstrange_deployment.yml
  .github/workflows/private_deployment.yml
  .github/workflows/qa_deployment.yml
  .github/workflows/staging_deployment.yml
Labels: size/M
