Repository fylein/fyle-intacct-api, pull requests merged in 2025-01, with the labels that each got.

#587 Feat: Add created_by, updated_by to conf tables
  apps/fyle/migrations/0036_auto_20250108_0702.py
  apps/fyle/models.py
  apps/fyle/views.py
  apps/mappings/migrations/0016_auto_20250108_0702.py
  apps/mappings/models.py
  apps/workspaces/apis/advanced_settings/serializers.py
  apps/workspaces/apis/advanced_settings/views.py
  apps/workspaces/apis/export_settings/serializers.py
  apps/workspaces/apis/export_settings/views.py
  apps/workspaces/apis/import_settings/serializers.py
  apps/workspaces/apis/import_settings/views.py
  apps/workspaces/migrations/0041_auto_20250108_0702.py
  apps/workspaces/models.py
  requirements.txt
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_fyle/fixtures.py
  tests/test_fyle/test_models.py
  tests/test_workspaces/fixtures.py
Labels: size/M

#588 fix: lib dependencies
  apps/fyle/models.py
  fyle_intacct_api/sentry.py
  fyle_intacct_api/settings.py
  fyle_intacct_api/tests/settings.py
  requirements.txt
Labels: size/S

#589 chore: add pytz
  requirements.txt
Labels: size/XS

#590 fix: django version
  apps/fyle/models.py
  requirements.txt
Labels: size/XS

#592 fix: get the key safely
  apps/sage_intacct/models.py
Labels: size/XS

#596 Feat: Resolved migration issue
  apps/internal/migrations/0001_auto_generated_sql.py
  apps/tasks/migrations/0001_initial.py
Labels: size/XS

#601 fix: routing change
  apps/fyle/helpers.py
Labels: size/XS

#602 fix: get access token
  apps/fyle/helpers.py
  apps/workspaces/tasks.py
Labels: size/XS
