Repository fylein/fyle-intacct-api, pull requests merged in 2025-06, with the labels that each got.

#695 feat: Real-time exports, phase 2 - Intacct
  apps/fyle/helpers.py
  apps/fyle/signals.py
  apps/fyle/tasks.py
  apps/fyle/views.py
  apps/internal/tasks.py
  apps/sage_intacct/queue.py
  apps/sage_intacct/views.py
  apps/workspaces/actions.py
  apps/workspaces/apis/advanced_settings/serializers.py
  apps/workspaces/apis/advanced_settings/triggers.py
  apps/workspaces/migrations/0045_workspaceschedule_is_real_time_export_enabled.py
  apps/workspaces/models.py
  apps/workspaces/tasks.py
  apps/workspaces/urls.py
  apps/workspaces/views.py
  requirements.txt
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_fyle/fixtures.py
  tests/test_fyle/test_signals.py
  tests/test_workspaces/fixtures.py
  tests/test_workspaces/test_apis/test_advanced_settings/fixtures.py
  tests/test_workspaces/test_tasks.py
  tests/test_workspaces/test_views.py
  workers/export/worker.py
Labels: size/L

#703 fix: Migrations
  apps/workspaces/migrations/0046_merge_20250603_1307.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
Labels: size/S

#704 Feat: Fix Allocation issue, when its an empty array
  apps/sage_intacct/utils.py
Labels: size/XS

#638 chore: UDD attribute_type update
  scripts/python/update-user-defined-attribute-type.py
Labels: size/M

#707 chore: Comment Patch Intergation Settings
  fyle_intacct_api/utils.py
  tests/test_sageintacct/test_utils.py
Labels: size/S

#697 Feat: Customisable top level memo
  .github/workflows/pytest.yml
  apps/sage_intacct/models.py
  apps/workspaces/apis/advanced_settings/serializers.py
  apps/workspaces/migrations/0047_configuration_top_level_memo_structure.py
  apps/workspaces/models.py
  tests/sql_fixtures/reset_db_fixtures/reset_db.sql
  tests/test_sageintacct/test_models.py
  tests/test_workspaces/fixtures.py
  tests/test_workspaces/test_apis/test_advanced_settings/fixtures.py
Labels: deploy, size/L

#712 feat: add Gitleaks secrets scan workflow
  .github/workflows/secrets-scan.yaml
Labels: size/S

#717 fix: handle expired creds
  apps/mappings/signals.py
  apps/mappings/tasks.py
  tests/test_mappings/test_signals.py
Labels: size/S

#718 fix: Timeout Warning
  fyle_intacct_api/settings.py
Labels: size/XS

#720 fix: Add CODEOWNERS for package.json and requirements.txt
  .github/CODEOWNERS
Labels: size/XS

#727 feat: add github hooks
  .pre-commit-config.yaml
Labels: size/S

#730 fix: pre commit
  .pre-commit-config.yaml
Labels: size/XS

#723 chore: run export tasks in rabbitmq worker
  apps/fyle/tasks.py
  apps/sage_intacct/queue.py
  apps/sage_intacct/tasks.py
  apps/workspaces/actions.py
  tests/test_fyle/test_queue.py
  tests/test_sageintacct/test_tasks.py
Labels: size/L

#734 fix: import in worker
  workers/export/worker.py
Labels: deploy, size/XS
