Repository fylein/fyle-intacct-api, pull requests merged in 2025-02, with the labels that each got.

#603 fix: hulk deployment
  .github/workflows/hulk_deployment.yaml
Labels: size/XS

#605 feat: Re export Stuck Exports
  apps/internal/migrations/0005_auto_generated_sql.py
  apps/internal/tasks.py
Labels: size/M

#611 test: patch integrations on errors
  tests/test_sageintacct/fixtures.py
  tests/test_sageintacct/test_tasks.py
Labels: size/M

#612 feat: Add support for optional dependent fields sync
  apps/fyle/helpers.py
  requirements.txt
Labels: size/XS

#615 fix: sentry pii
  fyle_intacct_api/sentry.py
Labels: size/M

#608 feat: skip export v2
  apps/fyle/actions.py
  apps/fyle/helpers.py
  apps/fyle/signals.py
  apps/fyle/tasks.py
  tests/test_fyle/fixtures.py
  tests/test_fyle/test_task.py
Labels: size/L

#616 fix: remove print statements
  tests/test_fyle/test_task.py
Labels: size/S

#617 fix: Medium vulnerabilities
  requirements.txt
Labels: size/XS
